=== scummvm/scummvm/devtools/create_ultima/files/ultima4/conf/dtd/maps.dtd
<!-- $Id: maps.dtd 2572 2005-10-03 06:17:52Z andrewtaylor $ -->

<!ENTITY % bool '( true | false )'>
<!ENTITY % role '( armorvendor | companion | foodvendor | guildvendor | hawkwind | healer | 
                   horsevendor | innkeeper | lordbritish | reagentsvendor | tavernkeeper |
                   weaponsvendor )'>

<!ELEMENT maps ( map+ ) >

<!ELEMENT map ( city | compressedchunk | dungeon | moongate | portal | shrine | xml | label )* >
<!ATTLIST map id                  NMTOKEN  #REQUIRED
              type                ( city | combat | dungeon | shrine | world | u3world ) #REQUIRED
              fname               NMTOKEN  #REQUIRED
              width               NMTOKEN  #REQUIRED
              height              NMTOKEN  #REQUIRED
              levels              NMTOKEN  #REQUIRED
              chunkwidth          NMTOKEN  #IMPLIED
              chunkheight         NMTOKEN  #IMPLIED
              offset              NMTOKEN  #IMPLIED
              borderbehavior      ( exit | fixed | wrap ) #REQUIRED
              showavatar          %bool;   #IMPLIED
              nolineofsight       %bool;   #IMPLIED
              firstperson         %bool;   #IMPLIED
              contextual          %bool;   #IMPLIED
              music               NMTOKEN  #REQUIRED
              tileset             NMTOKEN  #REQUIRED
              tilemap             NMTOKEN  #REQUIRED>

<!-- city-map specific information -->
<!ELEMENT city ( personrole* ) >
<!ATTLIST city name               CDATA    #REQUIRED
               type               ( castle | towne | village | ruins ) #REQUIRED
               tlk_fname          NMTOKEN  #REQUIRED>

<!-- special roles for persons in a city: e.g. vendors -->
<!ELEMENT personrole EMPTY >
<!ATTLIST personrole role         %role;   #REQUIRED
                     id           NMTOKEN  #REQUIRED>

<!-- the U5 map implicitly leaves out certain chunks that are all of value 0x01 -->
<!ELEMENT compressedchunk EMPTY >
<!ATTLIST compressedchunk index    NMTOKEN  #REQUIRED>

<!-- dungeon-map specific information -->
<!ELEMENT dungeon EMPTY >
<!ATTLIST dungeon name            CDATA    #REQUIRED
                  rooms           NMTOKEN  #REQUIRED>

<!-- shrine-map specific information -->
<!ELEMENT shrine EMPTY >
<!ATTLIST shrine mantra           NMTOKEN  #REQUIRED
                 virtue           NMTOKEN  #REQUIRED>

<!-- moongate definitions -->
<!ELEMENT moongate EMPTY >
<!ATTLIST moongate phase          NMTOKEN  #REQUIRED
                   x              NMTOKEN  #REQUIRED
                   y              NMTOKEN  #REQUIRED>

<!-- portals to other maps -->
<!ELEMENT portal ( retroActiveDest? ) >
<!ATTLIST portal x                NMTOKEN  #REQUIRED
                 y                NMTOKEN  #REQUIRED
                 z                NMTOKEN  #IMPLIED
                 destmapid        NMTOKEN  #REQUIRED
                 startx           NMTOKEN  #REQUIRED
                 starty           NMTOKEN  #REQUIRED
                 startlevel       NMTOKEN  #IMPLIED
                 action           ( descend | enter | klimb | exit_north | exit_east | exit_south | exit_west ) #REQUIRED
                 condition        ( shrine | abyss ) #IMPLIED
                 savelocation     %bool;   #REQUIRED
                 message          CDATA    #IMPLIED
                 transport        ( foot | footorhorse ) #REQUIRED
                 exits            NMTOKEN  #IMPLIED>

<!-- support for portals that don't exit where they are entered -->
<!ELEMENT retroActiveDest EMPTY >
<!ATTLIST retroActiveDest x       NMTOKEN  #REQUIRED
                          y       NMTOKEN  #REQUIRED
                          z       NMTOKEN  #IMPLIED
                          mapid   NMTOKEN  #REQUIRED>

<!-- labeled points of interest -->
<!ELEMENT label EMPTY >
<!ATTLIST label name    NMTOKEN  #REQUIRED
                x       NMTOKEN  #REQUIRED
                y       NMTOKEN  #REQUIRED
                z       NMTOKEN  #IMPLIED>

=== scummvm/scummvm/devtools/create_ultima/files/ultima4/conf/maps.xml
<?xml version="1.0"?>
<!DOCTYPE maps SYSTEM "dtd/maps.dtd">
<!-- $Id: maps.xml 2734 2010-12-13 18:24:16Z darren_janeczek $ -->
<maps>
    <!-- world map -->
    <map id="0" type="world" fname="world.map" width="256" height="256" levels="1" chunkwidth="32" chunkheight="32" 
     borderbehavior="wrap" showavatar="true" music="1" tileset="base" tilemap="base">
        <portal x="86"  y="107" destmapid="1"  startx="15" starty="30" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="218" y="107" destmapid="2"  startx="15" starty="30" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="28"  y="50"  destmapid="3"  startx="15" starty="30" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="146" y="241" destmapid="4"  startx="15" starty="30" action="enter" savelocation="true" transport="footorhorse"/>

        <portal x="232" y="135" destmapid="5"  startx="1" starty="15" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="82"  y="106" destmapid="6"  startx="1" starty="15" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="36"  y="222" destmapid="7"  startx="1" starty="15" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="58"  y="43"  destmapid="8"  startx="1" starty="15" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="159" y="20"  destmapid="9"  startx="1" starty="15" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="106" y="184" destmapid="10" startx="1" starty="15" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="22"  y="128" destmapid="11" startx="1" starty="15" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="187" y="169" destmapid="12" startx="1" starty="15" action="enter" savelocation="true" transport="footorhorse"/>

        <portal x="98"  y="145" destmapid="13" startx="1" starty="15" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="136" y="158" destmapid="14" startx="1" starty="15" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="201" y="59"  destmapid="15" startx="1" starty="15" action="enter" savelocation="true" transport="footorhorse"/>
        <portal x="136" y="90"  destmapid="16" startx="1" starty="15" action="enter" savelocation="true" transport="footorhorse"/>
        
        <portal x="240" y="73"  destmapid="17" startx="1" starty="1" action="enter" savelocation="true" transport="foot"/>
        <portal x="91"  y="67"  destmapid="18" startx="1" starty="1" action="enter" savelocation="true" transport="foot"/>
        <portal x="72"  y="168" destmapid="19" startx="1" starty="1" action="enter" savelocation="true" transport="foot"/>
        <portal x="126" y="20"  destmapid="20" startx="1" starty="1" action="enter" savelocation="true" transport="foot"/>
        <portal x="156" y="27"  destmapid="21" startx="1" starty="1" action="enter" savelocation="true" transport="foot"/>
        <portal x="58"  y="102" destmapid="22" startx="1" starty="1" action="enter" savelocation="true" transport="foot"/>
        <portal x="239" y="240" destmapid="23" startx="1" starty="1" action="enter" savelocation="true" transport="foot"/>
        <portal x="233" y="233" destmapid="24" startx="1" starty="1" action="enter" condition="abyss" savelocation="true" message="Enter the Great Stygian Abyss!&#xA;&#xA;" transport="foot"/>

        <portal x="233" y="66"  destmapid="25" startx="0" starty="0" action="enter" condition="shrine" savelocation="true" transport="footorhorse"/>
        <portal x="128" y="92"  destmapid="26" startx="0" starty="0" action="enter" condition="shrine" savelocation="true" transport="footorhorse"/>
        <portal x="36"  y="229" destmapid="27" startx="0" starty="0" action="enter" condition="shrine" savelocation="true" transport="footorhorse"/>
        <portal x="73"  y="11"  destmapid="28" startx="0" starty="0" action="enter" condition="shrine" savelocation="true" transport="footorhorse"/>
        <portal x="205" y="45"  destmapid="29" startx="0" starty="0" action="enter" condition="shrine" savelocation="true" transport="footorhorse"/>
        <portal x="81"  y="207" destmapid="30" startx="0" starty="0" action="enter" condition="shrine" savelocation="true" transport="footorhorse"/>
        <portal x="231" y="216" destmapid="32" startx="0" starty="0" action="enter" condition="shrine" savelocation="true" transport="footorhorse"/>

		<portal x="102" y="105" destmapid="101"  startx="1" starty="5" action="enter" savelocation="true" transport="footorhorse" tile="5"/>

		<moongate phase="0" x="224" y="133"/>
        <moongate phase="1" x="96" y="102"/>
        <moongate phase="2" x="38" y="224"/>
        <moongate phase="3" x="50" y="37"/>
        <moongate phase="4" x="166" y="19"/>
        <moongate phase="5" x="104" y="194"/>
        <moongate phase="6" x="23" y="126"/>
        <moongate phase="7" x="187" y="167"/>

        <!-- labels for other points of interest -->
        <label name="balloon"     x="233" y="242"/>
        <label name="lockelake"   x="127" y="78"/>
        <label name="mandrake1"   x="182" y="54"/>
        <label name="mandrake2"   x="100" y="165"/>
        <label name="nightshade1" x="46"  y="149"/>
        <label name="nightshade2" x="205" y="44"/>
        <label name="bell"        x="176" y="208"/>
        <label name="horn"        x="45"  y="173"/>
        <label name="wheel"       x="96"  y="215"/>
        <label name="skull"       x="197" y="245"/>
        <label name="blackstone"  x="224" y="133"/>
        <label name="whitestone"  x="64"  y="80"/>
        <label name="lasergun"    x="48"  y="22"/>
    </map>

    <!-- castles -->
    <map id="1" type="city" fname="lcb_1.ult" width="32" height="32" levels="1" 
     borderbehavior="exit" showavatar="true" music="9" tileset="base" tilemap="base">
        <city name="Britannia" type="castle" tlk_fname="lcb.tlk">
            <personrole role="healer" id="29"/>
            <personrole role="hawkwind" id="30"/>
        </city>
        <portal x="3" y="3" destmapid="100" startx="3" starty="3" action="klimb" savelocation="false" message="Klimb to second floor!&#xA;" transport="foot"/>
        <portal x="27" y="3" destmapid="100" startx="27" starty="3" action="klimb" savelocation="false" message="Klimb to second floor!&#xA;" transport="foot"/>
        <portal x="7" y="2" destmapid="23" startx="5" starty="5" action="descend" savelocation="false" message="Descend into the depths!&#xA;" transport="foot">
            <retroActiveDest x="239" y="240" mapid="0"/>
        </portal>
        <label name="spiritualityrune" x="17" y="8"/>
    </map>
    <map id="100" type="city" fname="lcb_2.ult" width="32" height="32" levels="1" 
     borderbehavior="exit" showavatar="true" music="9" tileset="base" tilemap="base">
        <city name="Britannia" type="castle" tlk_fname="lcb.tlk">
            <personrole role="lordbritish" id="32"/>
        </city>
        <portal x="3" y="3" destmapid="1" startx="3" starty="3" action="descend" savelocation="false" message="Descend to first floor!&#xA;" transport="foot"/>
        <portal x="27" y="3" destmapid="1" startx="27" starty="3" action="descend" savelocation="false" message="Descend to first floor!&#xA;" transport="foot"/>
    </map>
    <map id="2" type="city" fname="lycaeum.ult" width="32" height="32" levels="1" 
     borderbehavior="exit" showavatar="true" music="9" tileset="base" tilemap="base">
        <city name="Lycaeum" type="castle" tlk_fname="lycaeum.tlk">
            <personrole role="healer" id="23"/>
        </city>
        <label name="book" x="6" y="6"/>
        <label name="telescope" x="22" y="3"/>
    </map>
    <map id="3" type="city" fname="empath.ult" width="32" height="32" levels="1" 
     borderbehavior="exit" showavatar="true" music="9" tileset="base" tilemap="base">
        <city name="Empath Abbey" type="castle" tlk_fname="empath.tlk">
            <personrole role="healer" id="30"/>
        </city>
        <label name="mysticarmor" x="22" y="4"/>
    </map>
    <map id="4" type="city" fname="serpent.ult" width="32" height="32" levels="1"
     borderbehavior="exit" showavatar="true" music="9" tileset="base" tilemap="base">
        <city name="Serpents Hold" type="castle" tlk_fname="serpent.tlk">
            <personrole role="healer" id="31"/>
        </city>
        <label name="mysticswords" x="8" y="15"/>
    </map>

    <!-- cities -->
    <map id="5" type="city" fname="moonglow.ult" width="32" height="32" levels="1"
     borderbehavior="exit" showavatar="true" music="2" tileset="base" tilemap="base">
        <city name="Moonglow" type="towne" tlk_fname="moonglow.tlk">
            <personrole role="companion" id="32"/>
            <personrole role="foodvendor" id="26"/>
            <personrole role="reagentsvendor" id="24"/>
            <personrole role="healer" id="25"/>
            <personrole role="innkeeper" id="30"/>
        </city>
        <label name="honestyrune" x="8" y="6"/>
    </map>
    <map id="6" type="city" fname="britain.ult" width="32" height="32" levels="1"
     borderbehavior="exit" showavatar="true" music="2" tileset="base" tilemap="base">
        <city name="Britain" type="towne" tlk_fname="britain.tlk">
            <personrole role="companion" id="32"/>
            <personrole role="weaponsvendor" id="29"/>
            <personrole role="armorvendor" id="28"/>
            <personrole role="foodvendor" id="27"/>
            <personrole role="tavernkeeper" id="26"/>
            <personrole role="healer" id="31"/>
            <personrole role="innkeeper" id="25"/>
        </city>
        <label name="compassionrune" x="25" y="1"/>
    </map>
    <map id="7" type="city" fname="jhelom.ult" width="32" height="32" levels="1"
     borderbehavior="exit" showavatar="true" music="2" tileset="base" tilemap="base">
